#!/bin/sh

set -e

CONFIG_FILE=deps/loom/simple_ne/rel/files/sys.config

if [ ! -e "$CONFIG_FILE" ]; then
    echo "Config file not present. Run 'make' first." >&2
    exit 1
fi

if [ $# -ne 3 ]; then
    echo "Usage: $0 JSON-FILE SOURCE DESTINATION" >&2
    echo "where JSON-FILE is a JSON file containing topology data," >&2
    echo "  and SOURCE is the name of the source endpoint," >&2
    echo "  and DESTINATION is the name of the destination endpoint." >&2
    exit 1
fi

erl -pa ebin -pa deps/*/ebin deps/loom/simple_ne/apps/*/ebin \
    -config "$CONFIG_FILE" \
    -noinput -eval "flowcompiler:main()" -- "$@"
