#!/bin/sh

set -e

CONFIG_FILE=deps/loom/simple_ne/rel/files/sys.config

if [ ! -e "$CONFIG_FILE" ]; then
    echo "Config file not present. Run 'make' first." >&2
    exit 1
fi

if [ $# -lt 3 ]; then
    echo "Usage: $0 [-demo] JSON-FILE-OR-NODE SOURCE DESTINATION [SWITCH ...]" >&2
    echo "where JSON-FILE-OR-NODE is either a JSON file containing topology data," >&2
    echo "      or the node name of a running Dobby node," >&2
    echo "  and SOURCE is the name of the source endpoint," >&2
    echo "  and DESTINATION is the name of the destination endpoint," >&2
    echo "  and SWITCH is zero or more switches to connect to." >&2
    echo "" >&2
    echo "Create a bidirectional flow between SOURCE and DESTINATION." >&2
    echo "" >&2
    echo "If no SWITCH is specified, Weave will wait for the switches" >&2
    echo "to connect to it on port 6653.  Each SWITCH may be either a" >&2
    echo "hostname or an IP address, optionally followed by a colon" >&2
    echo "and a port number." >&2
    echo "" >&2
    echo "If SOURCE has its 'use_bridge_rules' metadata entry set to true," >&2
    echo "DESTINATION can be a comma-separated list of endpoints.  In this" >&2
    echo "case, Weave will create flow rules that forward all packets from" >&2
    echo "SOURCE to each DESTINATION, and all packets from each DESTINATION" >&2
    echo "to SOURCE, without regards to source and destination IP addresses." >&2
    echo "" >&2
    echo "If the -demo flag is specified, publish flow rules to Dobby but do not" >&2
    echo "install them in the switches." >&2
    echo "------------------------------------------------------------" >&2
    echo "Or: $0 -tap DOBBY-NODE SOURCE DESTINATION [SWITCH ...]" >&2
    echo "" >&2
    echo "Find the flow between SOURCE and DESTINATION, and add a" >&2
    echo "'send to controller' action to each hop." >&2
    exit 1
fi

erl -pa ebin -pa deps/*/ebin deps/loom/simple_ne/apps/*/ebin \
    -name weave@127.0.0.1 \
    -setcookie dobby \
    -config "$CONFIG_FILE" \
    -noinput -eval "flowcompiler:main()" -extra "$@"
